### ISSUE TITLE
Will Djeddit updates break old instances due to slug?

### ISSUE THREAD

**Issue by Logmytech** [EatEmAll/django-djeddit#19]
```
def _genSlug(self):
        slug = slugify(self.title, to_lower=True, max_length=80)
        return slug
```
@EatEmAll This is the code you updated. You  removed `threadSlugPage` and made it into `slugPage` and removed `if self.slug:` checks.

What if there are old posts with no slug?
I'm not sure if it's gonna break, but I want  to be sure.

**Comment by EatEmAll** [comment]
I've ensured that existing Thread objects will have slugs by adding them in migrations/0004_thread_slug.py:

`from djeddit.models import Thread`


`def genSlugs(apps, schema_editor):`
`    for t in Thread.objects.all().iterator():`
`        t.save()`
