### ISSUE TITLE
Would you be interested into converting this into a pinax app and pinax project

### ISSUE THREAD

**Issue by Logmytech** [EatEmAll/django-djeddit#2]
This is just a suggestion.

You probably already know what pinax is. If not it is a project for resuable django apps.

Pinax already has many features you use implemented like likes. They have a separate app for likes.

But currently pinax lacks a reddit clone.

The app will have a much bigger community.

If you want to do this, here are things you can do. **I plan on doing these myself if I can. But I'm kinda dumb. lol**.

You can even implement community features like notifications, friends, email veification etc using the existing pinax apps.
It seems pinax even has threaded comments. I'm yet to find where it is.

Thanks for reading this! I hope you give a reply with your opinion.

**Comment by EatEmAll** [comment]
I wasn't familiar with the Pinax project. I'll have to familiarize myself with their apps & documentation before deciding if it's something I would like to pursue.
Thanks for the suggestion.

**Comment by Logmytech** [comment]
Seems like likes isn't the project for karma. There is an app called pinax-points for that. But it doesn't have docs on how to use it.
