### ISSUE TITLE
Tests are failing on Django 2.0

### ISSUE THREAD

**Issue by EatEmAll** [EatEmAll/django-djeddit#21]
I'm getting the following error across all tests when running on Django 2.0:
`AttributeError: module 'django.contrib.auth.middleware' has no attribute 'SessionAuthenticationMiddleware'`

**Comment by EatEmAll** [comment]
Support for Django 2.0 was added.

**Comment by Logmytech** [comment]
How did you fix the error with Django 2.0 that was popping up during tests
