### ISSUE TITLE
Old back links will break for existing djeddit sites since you removed my logic that checked for "_" in dev branch

### ISSUE THREAD

**Issue by Logmytech** [EatEmAll/django-djeddit#23]
This may be trivial since many users are not using Djeddit, but this would have been important if this were a big app.

You removed my checks for both "_" and "-" and left only "-".

Now if some one has linked back to Djeddit pages, these links will break. That is why I placed all those check to make sure `djeddit.com/my_topic/` would work as well as `djeddit.com/my-topic`.

This is bad for SEO and we will also have broken links, especially if the site is big.

@EatEmAll  What do you think about this?

**Comment by EatEmAll** [comment]
Although I wouldn't worry about back links, I have to agree that broken external links are a problem. 
I added the backwards compatibility back in this [commit](https://github.com/EatEmAll/django-djeddit/commit/44272feceb2873a92710d7a2e84bc554a405bd59/).
