### ISSUE TITLE
MAJOR SECURITY ISSUE: CSRF by other websites and plain links can be used to delete all topics

### ISSUE THREAD

**Issue by Logmytech** [EatEmAll/django-djeddit#27]
If you are SuperUser other websites can do a get request to the delete topic URL and delete all your topics.

You should never use GET requests for deleting or database changes. This is plain wrong.

Currently found bugs: 
1) Get requests for deleting important data. The app is very vulnerable to CSRF.

2) Hardcoded absolute URLs in JS instead of reverse or {% url 'name' tp.pk %}

**Comment by EatEmAll** [comment]
This issue was fixed in version 0.3.3
