### ISSUE TITLE
Implementing Reddit source code slug generation for shorter URLs

### ISSUE THREAD

**Issue by Logmytech** [EatEmAll/django-djeddit#3]
**Note: This may not be necessary since most sites that use this app won't have more than a few thousand posts**
I was searching around for how reddit generates slugs and found this
https://stackoverflow.com/questions/410485/whats-the-5-character-alphanumeric-id-in-reddit-url

You seem to be implementing thread links by primary keys currently. 
Instead you can use this method from reddit's source code.
Primary keys are OK but they get big in big communities where there are a lot of posts.
This is a short slug generated from the primary key but is shorter for big numbers.
It's just a shorter way to reperesent a primary key using alphanumeric representation.

```

def to_base(q, alphabet):
    if q < 0: raise ValueError, "must supply a positive integer"
    l = len(alphabet)
    converted = []
    while q != 0:
        q, r = divmod(q, l)
        converted.insert(0, alphabet[r])
    return "".join(converted) or '0'

def to36(q):
    return to_base(q, '0123456789abcdefghijklmnopqrstuvwxyz')

#and elsewhere, under the "Link" class:

@property
def _id36(self):
    return to36(self._id)

``````

**Comment by EatEmAll** [comment]
I'm closing this we've already implemented slugs using awesome-slugify
